"""edit user add has used

Revision ID: 78a7cfa6f775
Revises: b5870d4bf20c
Create Date: 2025-10-20 23:03:32.087145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a7cfa6f775'
down_revision: Union[str, Sequence[str], None] = 'b5870d4bf20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_free_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_free_used')
    # ### end Alembic commands ###
